// This file is auto-generated by TanStack Router. Do not edit.

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FriendsIndexRouteImport } from './routes/friends.index'
import { Route as DevicesIdRouteImport } from './routes/devices.$id'
import { Route as ApiAddFriendTokenRouteImport } from './routes/api.add-friend.$token'
import { Route as FriendsFriendIdAnalysesAnalysisIdRouteImport } from './routes/friends.$friendId.analyses.$analysisId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
})
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
})
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
})
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
})
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
})
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
})
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
})
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
})
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
})
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const FriendsIndexRoute = FriendsIndexRouteImport.update({
  id: '/friends/',
  path: '/friends/',
  getParentRoute: () => rootRouteImport,
})
const DevicesIdRoute = DevicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DevicesRoute,
})
const ApiAddFriendTokenRoute = ApiAddFriendTokenRouteImport.update({
  id: '/api/add-friend/$token',
  path: '/api/add-friend/$token',
  getParentRoute: () => rootRouteImport,
})
const FriendsFriendIdAnalysesAnalysisIdRoute =
  FriendsFriendIdAnalysesAnalysisIdRouteImport.update({
    id: '/friends/$friendId/analyses/$analysisId',
    path: '/friends/$friendId/analyses/$analysisId',
    getParentRoute: () => rootRouteImport,
  })

const DevicesRouteChildren = {
  DevicesIdRoute: DevicesIdRoute,
}

const DevicesRouteWithChildren =
  DevicesRoute._addFileChildren(DevicesRouteChildren)

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  DevicesRoute: DevicesRouteWithChildren,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  MapsRoute: MapsRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  FriendsIndexRoute: FriendsIndexRoute,
  ApiAddFriendTokenRoute: ApiAddFriendTokenRoute,
  FriendsFriendIdAnalysesAnalysisIdRoute:
    FriendsFriendIdAnalysesAnalysisIdRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
